import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/site-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <SiteHeader />
        <main className="min-h-[calc(100vh-56px-56px)]">{children}</main>
        <footer className="border-t bg-white">
          <div className="container mx-auto h-14 px-4 text-center text-sm text-gray-500 flex items-center justify-center">
            © 2025 ALX Polly. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
